language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.4
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "export JASMINE_BROWSER=firefox"
before_script:
 - "cd test/dummy && bundle exec rake db:migrate RAILS_ENV=test && cd ../.."
